import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import Header from "@/components/user-interfaces/header";
import Footer from "@/components/user-interfaces/footer";

const arimo = Arimo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={arimo.className}>
        <Providers>
          <Header />
          <div className="min-h-[calc(100vh-20.5rem-4rem)]">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
